stages:
  - prepare
  - test
  - release
  - trigger deploy
  - static scans
  - publish pages

variables:
  MYSQL_ROOT_PASSWORD: "root"
  MYSQL_DATABASE: "ota_tuf"
  MYSQL_USER: "ota_tuf"
  MYSQL_PASSWORD: "ota_tuf"
  # VAULT_ADDR: defined in GitLab variables
  # The same image have to be used by test and code coverage jobs:
  TEST_IMAGE: advancedtelematic/gitlab-jobs:0.2.5

build CI nginx:
  stage: prepare
  image: advancedtelematic/gitlab-jobs:0.2.5
  except:
    - schedules
  only:
    changes:
      - cli/src/test/resources/*
      - deploy/ci.nginx.Dockerfile
  tags:
    - docker-sock
    - vault-token
  script:
    - export VAULT_TOKEN=$(cat /opt/vault/token)
    - gitlab-docker-login $VAULT_ADDR
    - cd deploy && ./build-tuf-nginx.sh
    - docker push advancedtelematic/tuf-nginx:latest

test:
  stage: test
  except:
    - schedules
  services:
    - name: advancedtelematic/tuf-nginx:latest
      alias: tuf-nginx
    - name: mariadb:10.2
      alias: db
      command:
        - --character-set-server=utf8
        - --collation-server=utf8_unicode_ci
        - --max_connections=1000
  image: $TEST_IMAGE
  variables:
    DB_URL: "jdbc:mariadb://db:3306/ota_tuf"
    MTLS_REPOSERVER_URI: "https://tuf-nginx:8181/"
  before_script:
    - ./deploy/gitlab-db-setup.sh mysql db
  script:
    - sbt -sbt-dir ./.sbt -ivy ./.ivy2 clean coverage ut:test
  artifacts:
    paths:
      - "libtuf/target/scala-*/scoverage-data"
      - "libtuf/target/scala-*/src_managed"
      - "libtuf-server/target/scala-*/scoverage-data"
      - "libtuf-server/target/scala-*/src_managed"
      - "keyserver/target/scala-*/scoverage-data"
      - "keyserver/target/scala-*/src_managed"
      - "cli/target/scala-*/scoverage-data"
      - "cli/target/scala-*/src_managed"
      - "reposerver/target/scala-*/scoverage-data"
      - "reposerver/target/scala-*/src_managed"
  cache:
    paths:
      - .ivy2/
      - .sbt/

code coverage:
  extends: .report_scala_coverage
  allow_failure: true
  image: $TEST_IMAGE
  before_script:
    - sbt -sbt-dir ./.sbt -ivy ./.ivy2 coverageAggregate

release:
  stage: release
  except:
    - schedules
  only:
    refs:
      - master
  tags:
    - docker-sock
    - vault-token
  variables:
    AWS_BUCKET_ID: "ota-tuf-cli-releases"
    AWS_REGION: "eu-west-1"
  image: advancedtelematic/gitlab-jobs:0.2.5
  script:
    - git fetch origin
    - git describe
    - export VAULT_TOKEN=$(cat /opt/vault/token)
    - gitlab-docker-login $VAULT_ADDR
    - eval $(set-vault-env -v $VAULT_ADDR --secret gitlab/ats-aws-key --secret gitlab/maven-publish)
    - sbt -x -sbt-dir ./.sbt -ivy ./.ivy2 -batch release
  cache:
    paths:
      - .ivy2/
      - .sbt/

trigger dev reposerver deploy:
  stage: trigger deploy
  except:
    - schedules
  only:
    refs:
      - master
  variables:
    ENV: "dev"
    NEW_TAG: $CI_COMMIT_SHA
    SERVICE: tuf-reposerver
    CREATE_COMMIT: "true"
  trigger:
    project: OLP/EDGE/OTA/infra/deployment-descriptors
    branch: master

trigger dev keyserver deploy:
  stage: trigger deploy
  except:
    - schedules
  only:
    - master
  variables:
    ENV: "dev"
    NEW_TAG: $CI_COMMIT_SHA
    SERVICE: tuf-keyserver
    CREATE_COMMIT: "true"
  trigger:
    project: OLP/EDGE/OTA/infra/deployment-descriptors
    branch: master


trigger sit keyserver deploy:
  stage: trigger deploy
  except:
    - schedules
  only:
    - deploy/sit
  variables:
    ENV: "sit"
    NEW_TAG: $CI_COMMIT_SHA
    SERVICE: tuf-keyserver
    CREATE_COMMIT: "true"
  trigger:
    project: OLP/EDGE/OTA/infra/deployment-descriptors
    branch: master


trigger sit reposerver deploy:
  stage: trigger deploy
  except:
    - schedules
  only:
    - deploy/sit
  variables:
    ENV: "sit"
    NEW_TAG: $CI_COMMIT_SHA
    SERVICE: tuf-reposerver
    CREATE_COMMIT: "true"
  trigger:
    project: OLP/EDGE/OTA/infra/deployment-descriptors
    branch: master


include:
  - template: Secret-Detection.gitlab-ci.yml
  - template: Dependency-Scanning.gitlab-ci.yml
  - template: License-Scanning.gitlab-ci.yml
  - project: olp/edge/ota/infra/security
    ref: v0.0.9
    file: /shared.yaml
