= tuf command line tools

== Obtaining the binary

Binaries are compiled for each push to `master` and stored in https://ats-tuf-cli-releases.s3-eu-central-1.amazonaws.com/index.html[s3].

Download the archive file, unpack and run:

    tar xvf <file>
    cd garage-sign/
    bin/garage-sign --help

== Offline signing use case
// (aka PRO-3669)

1. User rotates root keys offline, see <<Rotate Root Keys>>. This
usually does not happen on the same machine where the targets are
pulled/pushed.

2. Pull targets

    garage-sign targets pull --repo myrepo

3. Add a target

   garage-sign targets add --repo myrepo \
   --format binary \
   --length 5877 \
   --name dashboards \
   --version 0.0.2 \
   --sha256 a0d3e88637d93e20e37b8eaf85fe8e8ac8ac5018337e881a452c85f8b64df0a4 \
   --hardwareids hwid01 \
   --url http://localhost/dashboards.json

4. Sign new targets.json

   garage-sign targets sign --repo myrepo --key-name <targets key used to rotate>

5. Push new targets.json

   garage-sign targets push --repo myrepo

== Rotate Root Keys

=== Rotate Repo Server Root Keys

1. Initialize a local ota-plus cache using credentials.zip downloaded
from ATS Garage:

    garage-sign init --repo myrepo --servertype reposerver --credentials credentials.zip --reposerver <reposerver uri>
+
or
+
    garage-sign init --repo myrepo --servertype reposerver --credentials credentials.zip

2. Generate new root and target keys

    garage-sign key generate --repo myrepo --name myrepo-root --type ed25519

    garage-sign key generate --repo myrepo --name myrepo-targets --type ed25519

3. Rotate Root Keys

    garage-sign move-offline --repo myrepo --new-root myrepo-root \
    --new-targets myrepo-targets --old-root-alias old-root

4. Check repository

    tree tuf/myrepo/

    tuf/myrepo
    ├── auth.json
    ├── keys
    │   ├── myrepo-root.pub
    │   ├── myrepo-root.sec
    │   ├── myrepo-targets.pub
    │   ├── myrepo-targets.sec
    │   ├── old-root.pub
    │   └── old-root.sec
    └── roles
        └── root.json

    cat tuf/myrepo/root.json

5. It is recommended that at this point you sign `targets.json` with
the new keys and upload it to reposerver, otherwise clients will get
an error when trying to validate the old `targets.json`, retrieved by
the server, with the new `root.json`.

    cat tuf/myrepo/roles/unsigned/targets.json

    # verify unsigned targets.json, this should have been pulled
    # during `rotate`.

    garage-sign targets sign --repo myrepo --key-name targets

    garage-sign targets push --repo myrepo

==== Exporting credentials

After <<Rotate Root Keys>>, you will need the new `root.json` and keys
to sign targets using `targets-sign`. If the user signing the new
targets is not the same as the user rotating the root keys, you'll
need to export the new credentials:

    garage-sign  export-credentials --repo myrepo --target-key-name targets --to creds_export.zip

=== Rotate Director Root Keys

Target keys and meta data are managed by the director even in the offline case, so they don't
need to be dealt with here.

1. Initialize a local ota-plus cache using credentials.zip downloaded
from ATS Garage:

    garage-sign init --repo myrepo --servertype director --credentials credentials.zip --reposerver <reposerver uri>
+
or
+
    garage-sign init --repo myrepo --servertype director --credentials credentials.zip

2. Generate new root and target keys

    garage-sign key generate --repo myrepo --name myrepo-root --type ed25519

3. Rotate Root Keys

    garage-sign move-offline --repo myrepo --new-root myrepo-root \
    --old-root-alias old-root

4. Check repository

    tree tuf/myrepo/

    tuf/myrepo
    ├── auth.json
    ├── keys
    │   ├── myrepo-root.pub
    │   ├── myrepo-root.sec
    │   ├── old-root.pub
    │   └── old-root.sec
    └── roles
        └── root.json

    cat tuf/myrepo/root.json

== Managing an offline root.json

A root.json can be managed entirely offline by a user using `garage-sign`.

This can be done by pulling a root with `root pull`, editing the root
using the `root key` commands, or directly editing the unsigned root
file, and signing the new root with `root sign`. The resulting root
can then be pushed to the server with `root push`.
