= tuf command line tools

== Obtaining the binary

Binaries are compiled for each push to `master` and stored in http://teamcity.prod01.internal.advancedtelematic.com:8111/viewType.html?buildTypeId=ota_tuf_BuildCliTools[teamcity].

Download the archive file, unpack and run:

    tar xvf <file>
    cd garage-sign/
    bin/garage-sign --help

== Offline sign use case (aka PRO-3669)

1. User rotates root keys offline, see <<Rotate Root Keys>>

2. Pull targets

    garage-sign targets pull --repo buchtel

3. Add a target

   garage-sign targets add --repo sm \
   --format binary \
   --length 5877 \
   --name dashboards \
   --version 0.0.2 \
   --sha256 a0d3e88637d93e20e37b8eaf85fe8e8ac8ac5018337e881a452c85f8b64df0a4 \
   --hardwareids hwid01 \
   --url http://localhost/dashboards.json

4. Sign new targets.json

   garage-sign targets sign --repo buchtel --key-name <targets key used to rotate> 

5. Push new targets.json

   garage-sign targets push --repo buchtel

== Rotate Root Keys

This is not compatible with the above use case as uploading a new
target item with an offline root key is not supported. After rotating
root keys to offline storage root.json and it's key mapping need to be
maintained offline by the user.

1. Initialize a local ota-plus cache using credentials.zip downloaded from ATS Garage or treehub.json inside of it:

    garage-sign init --repo buchtel --credentials treehub.json
+
or
+
    garage-sign init --repo buchtel --credentials credentials.zip

2. Generate new root and target keys

    garage-sign gen-keys --repo buchtel --name buchtel-root --type ec
    
    garage-sign gen-keys --repo buchtel --name buchtel-targets --type ec
    
3. Rotate Root Keys

    garage-sign rotate --repo buchtel --new-root buchtel-root \
    --new-targets buchtel-targets --old-root-alias old-root

4. Check repository

    tree tuf/buchtel/

    tuf/buchtel
    ├── auth.json
    ├── keys
    │   ├── buchtel-root.pub
    │   ├── buchtel-root.sec
    │   ├── buchtel-targets.pub
    │   ├── buchtel-targets.sec
    │   ├── old-root.pub
    │   └── old-root.sec
    └── roles
        └── root.json

    cat tuf/buchtel/root.json
