= tuf command line tools

== Obtaining the binary

Binaries are compiled for each push to `master` and stored in https://ats-tuf-cli-releases.s3-eu-central-1.amazonaws.com/index.html[s3].

Download the archive file, unpack and run:

    tar xvf <file>
    cd garage-sign/
    bin/garage-sign --help

== Offline sign use case (aka PRO-3669)

1. User rotates root keys offline, see <<Rotate Root Keys>>. This
usually does not happen on the same machine where the targets are
pulled/pushed.

2. Pull targets

    garage-sign targets pull --repo buchtel

3. Add a target

   garage-sign targets add --repo buchtel \
   --format binary \
   --length 5877 \
   --name dashboards \
   --version 0.0.2 \
   --sha256 a0d3e88637d93e20e37b8eaf85fe8e8ac8ac5018337e881a452c85f8b64df0a4 \
   --hardwareids hwid01 \
   --url http://localhost/dashboards.json

4. Sign new targets.json

   garage-sign targets sign --repo buchtel --key-name <targets key used to rotate>

5. Push new targets.json

   garage-sign targets push --repo buchtel

== Rotate Root Keys

1. Initialize a local ota-plus cache using credentials.zip downloaded
from ATS Garage:

    garage-sign init --repo buchtel --credentials credentials.zip --reposerver <reposerver uri>
+
or
+
    garage-sign init --repo buchtel --credentials credentials.zip

2. Generate new root and target keys

    garage-sign gen-keys --repo buchtel --name buchtel-root --type ec
    
    garage-sign gen-keys --repo buchtel --name buchtel-targets --type ec
    
3. Rotate Root Keys

    garage-sign move-offline --repo buchtel --new-root buchtel-root \
    --new-targets buchtel-targets --old-root-alias old-root

4. Check repository

    tree tuf/buchtel/

    tuf/buchtel
    ├── auth.json
    ├── keys
    │   ├── buchtel-root.pub
    │   ├── buchtel-root.sec
    │   ├── buchtel-targets.pub
    │   ├── buchtel-targets.sec
    │   ├── old-root.pub
    │   └── old-root.sec
    └── roles
        └── root.json

    cat tuf/buchtel/root.json

5. It is recommended that at this point you sign `targets.json` with
the new keys and upload it to reposerver, otherwise clients will get
an error when trying to validate the old `targets.json`, retrieved by
the server, with the new `root.json`.

    cat tuf/buchtel/roles/unsigned/targets.json

    # verify unsigned targets.json, this should have been pulled
    # during `rotate`.

    garage-sign targets sign --repo buchtel --key-name targets

    garage-sign targets push --repo buchtel


== Managing an offline root.json

A root.json can be managed entirely offline by a user using `garage-sign`.

This can be done by pulling a root with `root pull`, editing the root
using the `root key` commands, or directly editing the unsigned root
file, and signing the new root with `root sign`. The resulting root
can then be pushed to the server with `root push`.

== Exporting credentials

After <<Rotate Root Keys>>, you will need the new `root.json` and keys
to sign targets using `targets-sign`. If the user signing the new
targets is not the same as the user rotating the root keys, you'll
need to export the new credentials:

    garage-sign  export-credentials --repo buchtel --target-key-name targets --to creds_export.zip
