ALTER DATABASE CHARACTER SET utf8 COLLATE utf8_unicode_ci;

CREATE TABLE `key_gen_requests` (
  `key_id` varchar(254) NOT NULL,
  `size` INTEGER NOT NULL,
  `status` ENUM('REQUESTED', 'GENERATED', 'ERROR') NOT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`key_id`)
)
;

CREATE TABLE `keys` (
  `key_id` varchar(254) NOT NULL,
  `key_type` ENUM('RSA') NOT NULL,
  public_key TEXT NOT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`key_id`)
)
;
